In [21]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

In [97]:
df=pd.read_excel('TestEDA.xlsx')

In [60]:
df.head()

Name  Point  Salary
0  Ashwin     10    5000
1  Partha      2    3000
2  Nandha      4  250000
3     Sai      6    6000
4    Hari     14   10000

In [10]:
df['Point'].skew() #0.60136

0.6013638196305305

In [34]:
df['Salary'].skew()#1.089

1.8094408785920368

# Inter Quarantile Method

Equal to the difference between 75th and 25th percentiles, or between upper and lower quartiles, IQR = Q3 − Q1

In [66]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

Point        6.0
Salary    5000.0
dtype: float64


In [69]:
df_num=df.select_dtypes(include='int')

In [76]:
Q1=df.quantile(0.25)
Q3=df.quantile(0.75)
IQR=Q3-Q1
print(Q1)
print(Q3)
print(IQR)
#Lower_Whisker = Q1 – 1.5*IQR
#Upper_Whisker = Q3 + 1.5*IQR
#print(Lower_Whisker, Upper_Whisker)

Point        4.0
Salary    5000.0
Name: 0.25, dtype: float64
Point        10.0
Salary    10000.0
Name: 0.75, dtype: float64
Point        6.0
Salary    5000.0
dtype: float64


In [85]:
df = df[~((df < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))).any(axis=1)]
df.shape

(4, 3)

In [86]:
df.head()

Name  Point  Salary
0  Ashwin     10    5000
1  Partha      2    3000
3     Sai      6    6000
4    Hari     14   10000

# Z-score Technique

Zscore re-scale and centre the data and looks for the points in 0 which is far from the threshold ,Threshold -3 t0 +3

In [99]:
df_num=df.select_dtypes(include='int64')

In [95]:
df_num.head()

Point  Salary
0     10    5000
1      2    3000
3      6    6000
4     14   10000

In [100]:
z = np.abs(stats.zscore(df_num))
print(z)

[[0.64993368 0.51010669]
 [1.2070197  0.5305929 ]
 [0.74278135 1.99945434]
 [0.27854301 0.49986358]
 [1.57841037 0.45889116]]


In [102]:
df_scaled=stats.zscore(df_num)

In [107]:
threshold = 3
print(np.where(z < 3))

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int64), array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))


In [105]:
df_scaled

array([[ 0.64993368, -0.51010669],
       [-1.2070197 , -0.5305929 ],
       [-0.74278135,  1.99945434],
       [-0.27854301, -0.49986358],
       [ 1.57841037, -0.45889116]])

In [108]:
df_scaled=df_num.apply(zscore)

In [109]:
df_scaled

Point    Salary
0  0.649934 -0.510107
1 -1.207020 -0.530593
2 -0.742781  1.999454
3 -0.278543 -0.499864
4  1.578410 -0.458891

In [113]:
df_scaled = df_scaled[(z < 3).all(axis=1)]
df_scaled

Point    Salary
0  0.649934 -0.510107
1 -1.207020 -0.530593
2 -0.742781  1.999454
3 -0.278543 -0.499864
4  1.578410 -0.458891