<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**

**Import the NumPy library before solving the exercises**

In [ ]:
import numpy as np

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [ ]:
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
array_temperature = np.array(list_temperature)

# check the type of 'array_temperature'
print(type(array_temperature))

# print the array
print('The array is:', array_temperature)

<class 'numpy.ndarray'>
The array is: [3.04 1.65 5.76 1.66 1.54 4.69 2.68]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [ ]:
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

# create a 1D array of 'weights'
array_weights = np.array(weights)

# retrieve the weights greater than 68
print('weights greater than 68:', array_weights[array_weights > 68])

weights greater than 68: [74.2 85.  74.  70.5 86.  82. ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Explanation:** It is possible to generate same random numbers everytime. There is a function called, random.seed() in numpy which gives the same random numbers everytime. It is necessary to set the random seed just before generating the random numbers to get the same values

In [ ]:
# set the random seed
# different values for 'seed' parameter gives different set of random numbers
np.random.seed(seed = 1025)

# 10 random integers from 20 to 40
np.random.randint(20, 40, 10)

array([38, 28, 23, 25, 30, 27, 21, 29, 25, 33])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
# array of 1st five positive integers
values = np.array(range(1,6))

print('Values', values)
print('Fifth power of values:', np.power(values, 5))

Values [1 2 3 4 5]
Fifth power of values: [   1   32  243 1024 3125]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
array_num = np.arange(51,100,2)

print('Array of odd integers from 51 to 100: \n', array_num)

Array of odd integers from 51 to 100: 
 [51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [ ]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
A = np.array(A)
print("The array is : \n", A)
# 'axis = 0' adds the elements column-wise
Sum = np.sum(A, axis= 0)
print("The colum sum is :",Sum)

The array is : 
 [[ 1  4  8]
 [ 5  7  3]
 [ 9 14  2]]
The colum sum is : [15 25 13]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [ ]:
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

# convert the list to array
array_num = np.asarray(num)

print('Element-wise remainder:', np.remainder(array_num, 8) )

Element-wise remainder: [2 7 2 6 0 3 5 0 4]


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
# create a 1D array of numbers from 1 to 20
array_1d = np.arange(20)
print('1D array:\n', array_1d)

# transform a 1D array to 2D array using 'reshape' function
# reshape(2,10) creates two arrays each of 10 elements
array_2d = array_1d.reshape(2,10)       
print('\n 2D array created from 1D array:\n', array_2d)

# retrieve the first five elements
print('\n The first 5 elements of 2nd array:', array_2d[1,0:5])

1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 2D array created from 1D array:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

 The first 5 elements of 2nd array: [10 11 12 13 14]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [ ]:
prices_monday = [10, 30, 50, 60, 90]
array_prices_monday = np.array(prices_monday)
print('array_1:', array_prices_monday)

prices_tuesday = [50, 20, 80, 125, 10, 70]
array_prices_tuesday = np.array(prices_tuesday)
print('array_2:', prices_tuesday)

print('Common values between two arrays:', np.intersect1d(array_prices_monday, array_prices_tuesday))

array_1: [10 30 50 60 90]
array_2: [50, 20, 80, 125, 10, 70]
Common values between two arrays: [10 50]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [ ]:
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]

# convert the list to array
array_weights = np.array(weights)
array_heights = np.array(heights)

# formula to calculate BMI
# 5**2: will give the square of 5 
BMI = array_weights/array_heights**2

print('BMI:', BMI)

BMI: [22.54657648 22.53061224 19.59645812 21.46915048 26.39797739 20.9572742
 23.922423  ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [ ]:
array1 = [[[3, 4], [8, 2],[5, 9]]]
array1 = np.array(array1)

# add a column '[5, 7 ]' to array1
new_array = np.insert(array1, obj= 3 , values= [5,7], axis= 1)
print('Updated array:', new_array)

Updated array: [[[3 4]
  [8 2]
  [5 9]
  [5 7]]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
# eye() creates a diagonal matrix
identity_5 = np.eye(5)
print('Identity matrix of order 5: \n', identity_5)

Identity matrix of order 5: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [ ]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
M = np.array(M)
print('Original Matrix: \n', M)

# transpose the matrix
M_trans = np.transpose(M)
print('\n Transpose of matrix M: \n', M_trans)

Original Matrix: 
 [[15 17 45 56]
 [ 7 42 15 63]
 [54  3 61 41]
 [ 0 87 16 20]]

 Transpose of matrix M: 
 [[15  7 54  0]
 [17 42  3 87]
 [45 15 61 16]
 [56 63 41 20]]


<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [ ]:
A1 = [[5, 9], [7, 6]]
A1 = np.array(A1)
print('A1: \n', A1)

A2 = [[8,-7], [0,4]]
A2 = np.array(A2)
print('A2: \n', A2)

# combine A2 with A1 vertically
updated_array = np.vstack((A1, A2))

print('\n The combined array is: \n', updated_array)

A1: 
 [[5 9]
 [7 6]]
A2: 
 [[ 8 -7]
 [ 0  4]]

 The combined array is: 
 [[ 5  9]
 [ 7  6]
 [ 8 -7]
 [ 0  4]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [ ]:
A1 = [[-81, 75, 40], [27, 67, 52]]
A1 = np.array(A1)
print('A1: \n', A1)

A2 = [[15, 54], [39, 56]]
A2 = np.array(A2)
print('A2: \n', A2)

# combine A2 with A1 horizontally
updated_array = np.hstack((A1, A2))

print('\n The combined array is: \n', updated_array)

A1: 
 [[-81  75  40]
 [ 27  67  52]]
A2: 
 [[15 54]
 [39 56]]

 The combined array is: 
 [[-81  75  40  15  54]
 [ 27  67  52  39  56]]


<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [ ]:
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]
A = np.array(A)
print('Original Array: \n', A)

# split the array into 3 sub-arrays containing two rows each
A_vertical_split = np.vsplit(A, 3)
print('\n A_1: \n', A_vertical_split[0])
print('\n A_2: \n', A_vertical_split[1])
print('\n A_3: \n', A_vertical_split[2])

Original Array: 
 [[ 4  7]
 [ 2 -3]
 [ 8  1]
 [ 0  9]
 [ 5 -1]
 [ 8  3]]

 A_1: 
 [[ 4  7]
 [ 2 -3]]

 A_2: 
 [[8 1]
 [0 9]]

 A_3: 
 [[ 5 -1]
 [ 8  3]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [ ]:
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
B = np.array(B)

print('Original Array: \n', B)

# split the array into two sub-arrays containing two rows each
B_horizontal_split = np.hsplit(B, 2)
print('\n B_1: \n', B_horizontal_split[0])
print('\n B_2: \n', B_horizontal_split[1])

Original Array: 
 [[ 8  7  0  9]
 [ 2 -3  5 10]
 [ 8  5 -1  3]]

 B_1: 
 [[ 8  7]
 [ 2 -3]
 [ 8  5]]

 B_2: 
 [[ 0  9]
 [ 5 10]
 [-1  3]]


<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [ ]:
L1 = [45, 67, 56, 71, 54, 62, 56]
L2 = [21, 52, 64, 10, 49, 74, 26]

for x,y in zip(L1,L2):       
    print(x,y)

45 21
67 52
56 64
71 10
54 49
62 74
56 26


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [ ]:
numbers = [6, 5, 3, 15]
numbers = np.array(numbers)
for x in numbers:
    print((2*x-1)/(x+5))

1.0
0.9
0.625
1.45


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Create an identity matrix with n dimensions (take input from the user). Fill the diagonals of that matrix with the multiples of the number provided by the user; take another input from the user. Consider the output below as an example </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="center">
    <td height = '100', width = '700'>
          <img src="que 20.png">
        </td>
</table>

In [ ]:
# take user input 
dim = int(input('Enter the dimension: '))
table = int(input('Enter the number to fill the diagonals with its multiples: '))

# create list of multiples
ls = [i*table for i in range(1,dim+1)]

# create an identity array
identity_array = np.identity(dim)

# using a for loop create the required martix
for i in range(0, len(identity_array)):
    identity_array[i][i] = ls[i]
    identity_array[len(identity_array)-1-i][i] = ls[i]

# print the matrix
identity_array

Enter the dimension: 3
Enter the number to fill the diagonals with its multiples: 5


array([[ 5.,  0., 15.],
       [ 0., 10.,  0.],
       [ 5.,  0., 15.]])