In [5]:
from sklearn.model_selection import KFold,LeaveOneOut,cross_val_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#KFold used to create test and Train for Cross validation test

In [4]:
dd=[1,2,3,4,5,6,7,8,9,10]
kf=KFold(n_splits=5)
for d1,d2 in kf.split(dd):
    print(d1,d2)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [8]:
X=[1,2,3,4,5,6,7,8,9]
Y=[10,20,30,40,50,60,70,80,90]
kf=KFold(n_splits=3)
for d1,d2 in kf.split(Y):
    x_train=np.asarray(X)[d1]
    Y_train=np.asarray(Y)[d1]
    x_test=np.asarray(X)[d2]
    Y_test=np.asarray(Y)[d2]
    print('\n')
    print('X_train: ',x_train,' Y_train: ',Y_train,)
    print('x_test: ',x_test,' Y_test: ',Y_test)



X_train:  [4 5 6 7 8 9]  Y_train:  [40 50 60 70 80 90]
x_test:  [1 2 3]  Y_test:  [10 20 30]


X_train:  [1 2 3 7 8 9]  Y_train:  [10 20 30 70 80 90]
x_test:  [4 5 6]  Y_test:  [40 50 60]


X_train:  [1 2 3 4 5 6]  Y_train:  [10 20 30 40 50 60]
x_test:  [7 8 9]  Y_test:  [70 80 90]


In [10]:
loo=LeaveOneOut()
for d1,d2 in loo.split(Y):
    x_train=np.asarray(X)[d1]
    Y_train=np.asarray(Y)[d1]
    x_test=np.asarray(X)[d2]
    Y_test=np.asarray(Y)[d2]
    print('\n')
    print('X_train: ',x_train,' Y_train: ',Y_train,)
    print('x_test: ',x_test,' Y_test: ',Y_test)



X_train:  [2 3 4 5 6 7 8 9]  Y_train:  [20 30 40 50 60 70 80 90]
x_test:  [1]  Y_test:  [10]


X_train:  [1 3 4 5 6 7 8 9]  Y_train:  [10 30 40 50 60 70 80 90]
x_test:  [2]  Y_test:  [20]


X_train:  [1 2 4 5 6 7 8 9]  Y_train:  [10 20 40 50 60 70 80 90]
x_test:  [3]  Y_test:  [30]


X_train:  [1 2 3 5 6 7 8 9]  Y_train:  [10 20 30 50 60 70 80 90]
x_test:  [4]  Y_test:  [40]


X_train:  [1 2 3 4 6 7 8 9]  Y_train:  [10 20 30 40 60 70 80 90]
x_test:  [5]  Y_test:  [50]


X_train:  [1 2 3 4 5 7 8 9]  Y_train:  [10 20 30 40 50 70 80 90]
x_test:  [6]  Y_test:  [60]


X_train:  [1 2 3 4 5 6 8 9]  Y_train:  [10 20 30 40 50 60 80 90]
x_test:  [7]  Y_test:  [70]


X_train:  [1 2 3 4 5 6 7 9]  Y_train:  [10 20 30 40 50 60 70 90]
x_test:  [8]  Y_test:  [80]


X_train:  [1 2 3 4 5 6 7 8]  Y_train:  [10 20 30 40 50 60 70 80]
x_test:  [9]  Y_test:  [90]


### Applying Cross Validation on Boston Data

In [9]:
from sklearn.datasets import load_boston
boston=load_boston()
bos=pd.DataFrame(boston.data,columns=boston.feature_names)
bos['price']=boston.target
bos=bos.sample(frac=1,random_state=4).reset_index(drop=True)

In [10]:
Y=bos['price']
X=bos.drop(['price','INDUS','AGE'],axis=1)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.33, random_state=42)

Train-Test Method

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

In [13]:
lir=LinearRegression(fit_intercept=True)
lir.fit(X_train,y_train)
y_train_pred=lir.predict(X_train)
r2_train=r2_score(y_train,y_train_pred)
rmse_train=np.sqrt(mean_squared_error(y_train,y_train_pred))
y_test_pred=lir.predict(X_test)
r2_test=r2_score(y_test,y_test_pred)
rmse_train=np.sqrt(mean_squared_error(y_test,y_test_pred))
print('R2 train',r2_train,'R2-Test',r2_test)

R2 train 0.7282942769350065 R2-Test 0.7571839237517559


In [20]:
Kf=KFold(n_splits=5)

In [21]:

i=1
for train_index,test_index in kf.split(Y):
    X_train=X.iloc[train_index]
    Y_train=Y[train_index]
    X_test=X.iloc[test_index]
    Y_test=Y[test_index]
    lir=LinearRegression(fit_intercept=True)
    lir.fit(X_train,y_train)
    y_train_pred=lir.predict(X_train)
    r2_train=r2_score(y_train,y_train_pred)
    rmse_train=np.sqrt(mean_squared_error(y_train,y_train_pred))
    y_test_pred=lir.predict(X_test)
    r2_test=r2_score(y_test,y_test_pred)
    rmse_train=np.sqrt(mean_squared_error(y_test,y_test_pred))
    print('fold',i,'R2-Train',r2_train,'R2-Test',r2_test)
    

NameError: name 'kf' is not defined

## To avoid above function use cross val score

In [7]:
import sklearn
sklearn.metrics.SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [18]:
lir=LinearRegression()
kfold=KFold(n_splits=5,shffule=True,random_state=5)
cv=cross_val_score(lir,X,Y,cv=kfold,scoring='r2')
cv ## From the five iteration getting Test score

array([0.72926545, 0.73489712, 0.74067434, 0.77127926, 0.66318346])

In [ ]:
loo=LeaveOneOut()
cv=cross_val_score(lir,X,Y,cv=loo,scoring='neg_mean_squared_error')
cvr=np.sqrt((cv*-1).mean())
cvr