In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('C:\\Ashwin\\Learning\\Workspace\\Workspace\\Capstone Project\\Practise\\data.csv')

In [4]:
df.head()

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0          1                                           0.370594          
1          1                                           0.464291          
2          1                                           0.426071          
3          1                                           0.399844          
4          1                                           0.465022          

    ROA(A) before interest and % after tax  \
0                                 0.424389   
1                                 0.538214   
2                                 0.499019   
3                                 0.451265   
4                                 0.538432   

    ROA(B) before interest and depreciation after tax  \
0                                           0.405750    
1                                           0.516730    
2                                           0.472295    
3                                           0.457733    
4                                           0.522298    

    Operating Gross Margin   Realized Sales Gross Margin  \
0                 0.601457                      0.601457   
1                 0.610235                      0.610235   
2                 0.601450                      0.601364   
3                 0.583541                      0.583541   
4                 0.598783                      0.598783   

    Operating Profit Rate   Pre-tax net Interest Rate  \
0                0.998969                    0.796887   
1                0.998946                    0.797380   
2                0.998857                    0.796403   
3                0.998700                    0.796967   
4                0.998973                    0.797366   

    After-tax net Interest Rate   Non-industry income and expenditure/revenue  \
0                      0.808809                                      0.302646   
1                      0.809301                                      0.303556   
2                      0.808388                                      0.302035   
3                      0.808966                                      0.303350   
4                      0.809304                                      0.303475   

   ...   Net Income to Total Assets   Total assets to GNP price  \
0  ...                     0.716845                    0.009219   
1  ...                     0.795297                    0.008323   
2  ...                     0.774670                    0.040003   
3  ...                     0.739555                    0.003252   
4  ...                     0.795016                    0.003878   

    No-credit Interval   Gross Profit to Sales  \
0             0.622879                0.601453   
1             0.623652                0.610237   
2             0.623841                0.601449   
3             0.622929                0.583538   
4             0.623521                0.598782   

    Net Income to Stockholder's Equity   Liability to Equity  \
0                             0.827890              0.290202   
1                             0.839969              0.283846   
2                             0.836774              0.290189   
3                             0.834697              0.281721   
4                             0.839973              0.278514   

    Degree of Financial Leverage (DFL)  \
0                             0.026601   
1                             0.264577   
2                             0.026555   
3                             0.026697   
4                             0.024752   

    Interest Coverage Ratio (Interest expense to EBIT)   Net Income Flag  \
0                                           0.564050                   1   
1                                           0.570175                   1   
2                                           0.563706                   1   
3                                           0.564663                   1   
4                        

In [6]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" " ,"_")
df.rename(columns = {'Bankrupt?' :'Bankrupt' },inplace=True)

In [ ]:
#Checking null/duplicate values

In [16]:
#Handling outlier
Q1 = df.quantile(0.01)
Q3 = df.quantile(0.99)
IQR = Q3 - Q1
df = df[~((df < (Q1-6*IQR)) | (df > (Q3 + 6*IQR))).any(axis = 1)]
df.shape

(6514, 96)

In [15]:
#Scaling data to same range
from sklearn.preprocessing import MinMaxScaler
minmax=MinMaxScaler()
df_scaled=minmax.fit_transform(df)
df_scaled=pd.DataFrame(data=df_scaled,columns=df.columns)
df_scaled.head()

Bankrupt  ROA(C)_before_interest_and_depreciation_before_interest  \
0       1.0                                           0.381454         
1       1.0                                           0.411561         
2       1.0                                           0.478649         
3       1.0                                           0.400070         
4       0.0                                           0.402378         

   ROA(A)_before_interest_and_%_after_tax  \
0                                0.420377   
1                                0.447439   
2                                0.535214   
3                                0.411100   
4                                0.441840   

   ROA(B)_before_interest_and_depreciation_after_tax  Operating_Gross_Margin  \
0                                           0.405750                0.709830   
1                                           0.457733                0.628209   
2                                           0.522298                0.697649   
3                                           0.419134                0.658415   
4                                           0.436158                0.794077   

   Realized_Sales_Gross_Margin  Operating_Profit_Rate  \
0                     0.707021               0.912856   
1                     0.625724               0.880983   
2                     0.694889               0.913320   
3                     0.656169               0.887885   
4                     0.790935               0.915685   

   Pre-tax_net_Interest_Rate  After-tax_net_Interest_Rate  \
0                   0.550915                     0.523433   
1                   0.555418                     0.533724   
2                   0.577930                     0.555996   
3                   0.551820                     0.520878   
4                   0.557954                     0.533381   

   Non-industry_income_and_expenditure/revenue  ...  \
0                                     0.411011  ...   
1                                     0.443784  ...   
2                                     0.449630  ...   
3                                     0.432889  ...   
4                                     0.418841  ...   

   Net_Income_to_Total_Assets  Total_assets_to_GNP_price  No-credit_Interval  \
0                    0.650414                   0.009119            0.459292   
1                    0.680432                   0.003151            0.459534   
2                    0.753743                   0.003776            0.462408   
3                    0.641922                   0.005177            0.457961   
4                    0.676552                   0.018272            0.463062   

   Gross_Profit_to_Sales  Net_Income_to_Stockholder's_Equity  \
0               0.709820                            0.796851   
1               0.628201                            0.850553   
2               0.697648                            0.892175   
3               0.658427                            0.813014   
4               0.794080                            0.813336   

   Liability_to_Equity  Degree_of_Financial_Leverage_(DFL)  \
0             0.135752                            0.260955   
1             0.060711                            0.261897   
2             0.032330                            0.242818   
3             0.090494                            0.261688   
4             0.156123                            0.261168   

   Interest_Coverage_Ratio_(Interest_expense_to_EBIT)  Net_Income_Flag  \
0                                           0.527779               0.0   
1                                           0.530599               0.0   
2                                           0.580957               0.0   
3                                           0.530023               0.0   
4                                           0.528468               0.0   

   Equity_to_Liability  
0             0.009952  
1             0.023846  
2             0.04

In [17]:
#Getting target and independent variables
input_cols=df_scaled.drop('Bankrupt',axis=1)
traget_cols=df_scaled['Bankrupt']

In [47]:
from sklearn.feature_selection import mutual_info_classif 
from imblearn.over_sampling import SMOTE 
mutual_info = mutual_info_classif(X= input_cols,y= traget_cols) 
pruned_features = input_cols.columns[np.where(mutual_info>0)]
input_cols_pruned = input_cols[pruned_features]
sm = SMOTE(random_state=123)
X_sm , y_sm = sm.fit_resample(input_cols_pruned,traget_cols)
print(f'''Shape of X before SMOTE:{input_cols_pruned.shape}
Shape of X after SMOTE:{X_sm.shape}''',"\n\n")
print(f'''Target Class distributuion before SMOTE:\n{traget_cols.value_counts(normalize=True)}
Target Class distributuion after SMOTE :\n{y_sm.value_counts(normalize=True)}''')

Shape of X before SMOTE:(6552, 90)
Shape of X after SMOTE:(12738, 90) 


Target Class distributuion before SMOTE:
0.0    0.97207
1.0    0.02793
Name: Bankrupt, dtype: float64
Target Class distributuion after SMOTE :
0.0    0.5
1.0    0.5
Name: Bankrupt, dtype: float64


In [60]:
from sklearn.model_selection import train_test_split,cross_val_score, GridSearchCV
x_train,x_test,y_train,y_test=train_test_split(X_sm,y_sm,test_size=0.3,random_state=30)

In [53]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, roc_auc_score, f1_score, precision_score

In [55]:
dt_model=RandomForestClassifier(max_depth=8,random_state=1,).fit(x_train,y_train)
y_pred=dt_model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9594453165881738
[[1757  138]
 [  17 1910]]


In [57]:
knnclassifier=KNeighborsClassifier(n_neighbors=2).fit(x_train,y_train)
y_pred=knnclassifier.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9756671899529042
[[1802   93]
 [   0 1927]]


In [61]:
#Cross validation for KNN
cross_val_score(estimator = knnclassifier, X = x_train, y = y_train, scoring = "accuracy", cv = 10)

array([0.97757848, 0.98542601, 0.97197309, 0.97085202, 0.97982063,
       0.96860987, 0.97530864, 0.97306397, 0.97867565, 0.97867565])

In [62]:
#Hyper parameter tuning for KNN Algorithm
params = [{"n_neighbors":[1,2,3,4,5]}]
knnclassifier = KNeighborsClassifier()
RF_grid = GridSearchCV(estimator = knnclassifier, param_grid = params, cv = 5, scoring = "recall")
RF_grid.fit(x_train,y_train)
RF_grid.best_params_

{'n_neighbors': 5}

In [63]:
#XGBoost
XGB = XGBClassifier(learning_rate = 0.01, gamma = 2, use_label_encoder = False, eval_metric = "logloss", n_estimators = 200, max_depth = 6)
XGB.fit(x_train, y_train)
y_pred=dt_model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
#print(classification_report(ytest, XGB.predict(xtest)))

0.9594453165881738
[[1757  138]
 [  17 1910]]


In [69]:
base_learners = [('KNN', KNeighborsClassifier()),
                 ('KNN1', KNeighborsClassifier()),
                ('KNN2', KNeighborsClassifier())]

stack_model_gdBoost = StackingClassifier(estimators = base_learners, final_estimator = KNeighborsClassifier())
stack_model_gdBoost.fit(x_train, y_train)
y_pred = stack_model_gdBoost.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.97854526425955
[[1822   73]
 [   9 1918]]


In [ ]:
#Hyper parameter Tuning
#params = [{"max_depth":[7,8,9,10,11], "max_features":[6,7,8,9], "n_estimators":[100,120,140,150]}]
#RF = RandomForestClassifier()
#RF_grid = GridSearchCV(estimator = RF, param_grid = params, cv = 5, scoring = "recall")
#RF_grid.fit(x_train,y_train)
#RF_grid.best_params_

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input_cols,traget_cols,test_size=0.3,random_state=30)

In [21]:
#Base model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import metrics
logreg=LogisticRegression()
logreg.fit(x_train,y_train)
log_pred=logreg.predict(x_test)
print('Accuracy:',accuracy_score(log_pred,y_test))
print('Confusion Matrix',confusion_matrix(log_pred,y_test))
print(metrics.classification_report(log_pred,y_test))

Accuracy: 0.9674465920651069
Confusion Matrix [[1897   58]
 [   6    5]]
              precision    recall  f1-score   support

         0.0       1.00      0.97      0.98      1955
         1.0       0.08      0.45      0.14        11

    accuracy                           0.97      1966
   macro avg       0.54      0.71      0.56      1966
weighted avg       0.99      0.97      0.98      1966



In [49]:
#Base model after Smote
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import metrics
logreg=LogisticRegression()
logreg.fit(x_train,y_train)
log_pred=logreg.predict(x_test)
print('Accuracy:',accuracy_score(log_pred,y_test))
print('Confusion Matrix',confusion_matrix(log_pred,y_test))
print(metrics.classification_report(log_pred,y_test))

Accuracy: 0.8901098901098901
Confusion Matrix [[1644  169]
 [ 251 1758]]
              precision    recall  f1-score   support

         0.0       0.87      0.91      0.89      1813
         1.0       0.91      0.88      0.89      2009

    accuracy                           0.89      3822
   macro avg       0.89      0.89      0.89      3822
weighted avg       0.89      0.89      0.89      3822



C:\Ashwin\Learning\Datascience\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
#Basemodel - Decision tree
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(x_train,y_train)
dtree_pred=dtree.predict(x_test)
print('Accuracy:',accuracy_score(dtree_pred,y_test))
print('Confusion Matrix',confusion_matrix(dtree_pred,y_test))
print(metrics.classification_report(dtree_pred,y_test))

Accuracy: 0.9491353001017294
Confusion Matrix [[1847   44]
 [  56   19]]
              precision    recall  f1-score   support

         0.0       0.97      0.98      0.97      1891
         1.0       0.30      0.25      0.28        75

    accuracy                           0.95      1966
   macro avg       0.64      0.62      0.62      1966
weighted avg       0.95      0.95      0.95      1966



In [50]:
#Basemodel - Decision tree after resamling
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(x_train,y_train)
dtree_pred=dtree.predict(x_test)
print('Accuracy:',accuracy_score(dtree_pred,y_test))
print('Confusion Matrix',confusion_matrix(dtree_pred,y_test))
print(metrics.classification_report(dtree_pred,y_test))

Accuracy: 0.9542124542124543
Confusion Matrix [[1786   66]
 [ 109 1861]]
              precision    recall  f1-score   support

         0.0       0.94      0.96      0.95      1852
         1.0       0.97      0.94      0.96      1970

    accuracy                           0.95      3822
   macro avg       0.95      0.95      0.95      3822
weighted avg       0.95      0.95      0.95      3822



In [36]:
#Applying PCA for 95% variance
from sklearn.decomposition import PCA
pca_again = PCA(0.95)
df_train_pca2 = pca_again.fit_transform(x_train)
df_train_pca2.shape
learner_pca2 = LogisticRegression()
model_pca2 = learner_pca2.fit(df_train_pca2,y_train)
df_test_pca2 = pca_again.transform(x_test)
df_test_pca2.shape
pred_probs_test2 = model_pca2.predict_proba(df_test_pca2)[:,1]
"{:2.2f}".format(metrics.roc_auc_score(y_test, pred_probs_test2))

'0.91'

In [51]:
#Applying PCA for 95% variance after sampling
from sklearn.decomposition import PCA
pca_again = PCA(0.95)
df_train_pca2 = pca_again.fit_transform(x_train)
df_train_pca2.shape
learner_pca2 = LogisticRegression()
model_pca2 = learner_pca2.fit(df_train_pca2,y_train)
df_test_pca2 = pca_again.transform(x_test)
df_test_pca2.shape
pred_probs_test2 = model_pca2.predict_proba(df_test_pca2)[:,1]
"{:2.2f}".format(metrics.roc_auc_score(y_test, pred_probs_test2))

'0.94'

In [37]:
#Ensemble technique - Gradient boosting
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier,AdaBoostClassifier
gbc = GradientBoostingClassifier(learning_rate=0.1,max_depth=2,random_state=123,subsample=0.8,n_estimators=600)
gbc_fit = gbc.fit(df_train_pca2,y_train)
gbc_pred = gbc_fit.predict_proba(df_test_pca2)
gbc_pred = gbc_pred[:,1]
gbc_fpr, gbc_tpr, _ = metrics.roc_curve(y_test,  gbc_pred)
gbc_auc = metrics.roc_auc_score(y_test,gbc_pred)
print('Gradient Boosted Classifier AUC=%.3f' % (gbc_auc))

Gradient Boosted Classifier AUC=0.882


In [52]:
#Ensemble technique - Gradient boosting after sampling
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier,AdaBoostClassifier
gbc = GradientBoostingClassifier(learning_rate=0.1,max_depth=2,random_state=123,subsample=0.8,n_estimators=600)
gbc_fit = gbc.fit(df_train_pca2,y_train)
gbc_pred = gbc_fit.predict_proba(df_test_pca2)
gbc_pred = gbc_pred[:,1]
gbc_fpr, gbc_tpr, _ = metrics.roc_curve(y_test,  gbc_pred)
gbc_auc = metrics.roc_auc_score(y_test,gbc_pred)
print('Gradient Boosted Classifier AUC=%.3f' % (gbc_auc))

Gradient Boosted Classifier AUC=0.981
