Convert a given string to int using a single line of code.

In [8]:
a='12345'
int(a)
#Write a code snippet to convert a string to a list.
b='ashwin'
#Two ways for converting a list
b.split(" ")
list(b)

['ashwin']

In [19]:
#Write a code snippet to reverse a string.
b='ashwin'
print("".join(reversed(b)))
b.split(" ")
print(b[::-1])

niwhsa
niwhsa


In [38]:
#Write a code snippet to sort a list in Python.
b='ashwin'
lis1=list(b)
print(sorted(b))
print(list(b).sort())
lis1.remove('a')

#List has no object as delete

['a', 'h', 'i', 'n', 's', 'w']
None


In [47]:
#Write a code snippet to reverse an array.
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2=np.array(list(reversed(arr1)))
arr2=np.delete(arr2,0)
arr2

array([3, 2, 1])

In [51]:
#concatenate list
List1= ['w','a','b','c']
List2 = ['e','log']

print(List1+List2)
print(List1.extend(List2))

['w', 'a', 'b', 'c', 'e', 'log']
None


In [52]:
#Write a code snippet to generate the square of every element of a list.
a=[1,2,3,4]
print([ i*i for i in a])

[1, 4, 9, 16]


In [59]:
#arange- returns numpy array similar to range
import numpy as np
for i in np.arange(0,10):
    i

In [1]:
import re
a='Hi @3#R$ there'
b=re.sub('[^a-zA-Z]','',a)
print(b)

HiRthere


In [5]:
nums = [10, 5, 8, 20, 3]
for i in nums:
    for j in range(0,len(nums)-1):
        if i > nums[j]:
            grt=i
            
print(grt)
        

20


In [16]:
#Write a Python program to reverse a string.
a='Hi @3#R$ there'
''.join(reversed(a))
a.split(' ')

['Hi', '@3#R$', 'there']

In [25]:
#Write a Python program to count the frequency of each element in list
nums = [10, 5, 8, 20, 3 , 5,8,5,8,10]
fre={}
for i in nums:
    if i in fre:
        fre[i]+=1
    else:
        fre[i]=1
fre

{10: 2, 5: 3, 8: 3, 20: 1, 3: 1}

In [30]:
#Write a Python program to find the common elements between two lists.
lis1 = [10, 5, 8, 20, 3 , 5,8,5,8,10,11]
lis2 = [20, 3 , 5,8,5,8,10]
import numpy as np
d=np.intersect1d(lis1, lis2)

[ i for i in lis1 if i in lis2]

[10, 5, 8, 20, 3, 5, 8, 5, 8, 10]

In [32]:
#Write a Python program to sort a list of elements 
lis2 = [20, 3 , 5,8,5,8,10]
import numpy as np
np.sort(lis2)

array([ 3,  5,  5,  8,  8, 10, 20])

In [37]:
#Write a Python program to find the second largest number in a list.
lis1 = [10, 5, 8, 20, 3 , 5,8,5,8,10,11]
import numpy as np
b=a[::-1]
b[1]

10

In [39]:
#Write a Python program to remove duplicates from a list.
lis1 = [10, 5, 8, 20, 3 , 5,8,5,8,10,11]
lis1=set(lis1)
list(lis1)

[3, 5, 8, 10, 11, 20]

In [46]:
#Write a program to find the sum of all numbers in a list. 
lis1 = [10, 5, 8, 20, 3 , 5,8,5,8,10,11]
sum=0
for i in lis1:
    sum=sum+i
print(sum)

93


In [52]:
#Write a program to check if a string is a palindrome. 
str1="MadaM"
if str1==''.join(reversed(str1)):
    print("palindrome")

palindrome


In [66]:
#Write a program to find the factorial of a number. 
num=8
fact=1
if num==0:
    print("0")
else:
    for i in range(2,num):
        fact*=i
print(fact)

5040


In [80]:
#Write a  Python function to reverse a list at a specific location.
lis1 = [10, 5, 8, 20, 3 , 5,8,5,8,10,11]
b=lis1[2:-1]
b[::-1]

[10, 8, 5, 8, 5, 3, 20, 8]

In [84]:
a=[1,2,3,4]
b=[5,6,7,8,1]
import numpy as np
print(np.union1d(a,b))
print(np.intersect1d(a,b))

[1 2 3 4 5 6 7 8]
[1]


In [95]:
lis1 = [10, 5, 8, 20, 3 , 5,8,5,8,10,11]
lis1.remove(10)

#list - insert,append  remove,pop

In [110]:
lis1 = {10, 5, 8, 20, 3, 5,8,5,8,10,11}
lis1.add(11)
lis1.update([1,2,3])
lis1.remove(10)
lis1.pop()
#set - add,update  remove,pop

1

In [143]:
a={1:'a',2:'b',3:'c'}
a.update({4:'d',5:'e'})
b=[6,7,8,9,10]
c=dict(zip(b,a.values()))
c[8]='Ashwin'
c

{6: 'a', 7: 'b', 8: 'Ashwin', 9: 'd', 10: 'e'}

In [144]:
c.update({11:'f',12:'g'})
c[12]='Giraffe'
c.pop(11)
c

{6: 'a', 7: 'b', 8: 'Ashwin', 9: 'd', 10: 'e', 12: 'Giraffe'}